-- ============================================================
-- ASCENDX AI — Neon: usa el reset completo actualizado
-- ============================================================
-- Este archivo queda como acceso rápido.
-- El SQL listo para COPIAR Y PEGAR en Neon es:
--
--   backend/prisma/neon-full-reset.sql
--
-- Ese script:
--   1) DROP SCHEMA public CASCADE  (borra la BD anterior)
--   2) Crea todo el esquema actual (Jul 2026)
--   3) Marca las migraciones Prisma como aplicadas
--
-- Después en tu PC (carpeta backend/):
--   1. DATABASE_URL en .env
--   2. npx prisma generate
--   3. npm run db:seed   (solo desarrollo)
--   4. npm run dev
-- ============================================================
