/** Campos públicos del usuario (auth, perfil, /user/me). */
export const USER_PROFILE_SELECT = {
  id: true,
  name: true,
  email: true,
  xp: true,
  level: true,
  plan: true,
  referralCode: true,
  streakShields: true,
  dailyFocus: true,
  dailyFocusDate: true,
  onboardingDone: true,
  productTourDone: true,
  pushToken: true,
  preferredCurrency: true,
  tradingJournalEnabled: true,
  subscriptionStatus: true,
  subscriptionPeriodEnd: true,
  emailOptIn: true,
  themePreference: true,
  accountabilityCode: true,
  morningRitualDoneDate: true,
  proTrialEndsAt: true,
  termsAcceptedAt: true,
  googleId: true,
  appleId: true,
  createdAt: true,
  updatedAt: true,
} as const;
